# Generated by Django 5.1.4 on 2025-02-20 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 12, 0)),
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
