# Generated by Django 5.1.4 on 2025-02-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_alter_submission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
